// src/app/api/test-papers/data.ts

export const questionBank = {
  math: [
    { id: "m1", question: "What is 15 + 10 ?", options: ["20", "25", "30", "35"], correctAnswer: "25" },
    { id: "m2", question: "What is 12 × 5 ?", options: ["50", "60", "70", "80"], correctAnswer: "60" },
    { id: "m3", question: "Square root of 81?", options: ["7", "8", "9", "10"], correctAnswer: "9" },
    { id: "m4", question: "What is 100 ÷ 4 ?", options: ["20", "25", "30", "40"], correctAnswer: "25" },
    { id: "m5", question: "What is 7² ?", options: ["49", "42", "56", "64"], correctAnswer: "49" },
    { id: "m6", question: "What is 25% of 200?", options: ["25", "50", "75", "100"], correctAnswer: "50" },
    { id: "m7", question: "What is 15 - 8 ?", options: ["5", "7", "9", "11"], correctAnswer: "7" },
    { id: "m8", question: "What is 9 × 9 ?", options: ["72", "81", "90", "99"], correctAnswer: "81" },
    { id: "m9", question: "What is 50% of 80?", options: ["20", "30", "40", "50"], correctAnswer: "40" },
    { id: "m10", question: "What is 3³ ?", options: ["9", "15", "27", "30"], correctAnswer: "27" },
    { id: "m11", question: "What is 144 ÷ 12?", options: ["10", "12", "14", "16"], correctAnswer: "12" },
    { id: "m12", question: "What is 2⁵?", options: ["10", "25", "32", "50"], correctAnswer: "32" },
    { id: "m13", question: "What is 11 × 11?", options: ["100", "110", "121", "131"], correctAnswer: "121" },
    { id: "m14", question: "What is 999 + 1?", options: ["900", "1000", "1100", "1200"], correctAnswer: "1000" },
    { id: "m15", question: "What is 7 × 8 ?", options: ["54", "56", "58", "60"], correctAnswer: "56" },
    { id: "m16", question: "Square root of 100?", options: ["9", "10", "11", "12"], correctAnswer: "10" },
    { id: "m17", question: "What is 6 × 6?", options: ["30", "36", "42", "48"], correctAnswer: "36" },
    { id: "m18", question: "What is 18 ÷ 3?", options: ["4", "6", "8", "10"], correctAnswer: "6" },
    { id: "m19", question: "What is 20 + 30 + 50?", options: ["90", "100", "110", "120"], correctAnswer: "100" },
    { id: "m20", question: "What is 15% of 100?", options: ["10", "15", "20", "25"], correctAnswer: "15" },
  ],
  reasoning: [
    { id: "r1", question: "Find the odd one out.", options: ["Apple", "Banana", "Car", "Orange"], correctAnswer: "Car" },
    { id: "r2", question: "2, 4, 8, 16, ?", options: ["20", "24", "32", "36"], correctAnswer: "32" },
    { id: "r3", question: "Dog : Puppy :: Cat : ?", options: ["Cub", "Kitten", "Baby", "Child"], correctAnswer: "Kitten" },
    { id: "r4", question: "Which is different?", options: ["Circle", "Square", "Triangle", "Car"], correctAnswer: "Car" },
    { id: "r5", question: "Sun rises in?", options: ["North", "South", "East", "West"], correctAnswer: "East" },
    { id: "r6", question: "1, 1, 2, 3, 5, 8, ?", options: ["10", "12", "13", "15"], correctAnswer: "13" },
    { id: "r7", question: "DBFH : ?", options: ["EGIK", "EGIL", "FHKL", "EGJL"], correctAnswer: "EGIK" },
    { id: "r8", question: "Odd one out", options: ["Pen", "Pencil", "Book", "Eraser"], correctAnswer: "Book" },
    { id: "r9", question: "5, 10, 15, 20, ?", options: ["24", "25", "26", "30"], correctAnswer: "25" },
    { id: "r10", question: "Red : Stop :: Green : ?", options: ["Go", "Wait", "Caution", "Slow"], correctAnswer: "Go" },
    { id: "r11", question: "Tiger : Animal :: Rose : ?", options: ["Flower", "Plant", "Tree", "Leaf"], correctAnswer: "Flower" },
    { id: "r12", question: "3, 6, 12, 24, ?", options: ["36", "40", "48", "50"], correctAnswer: "48" },
    { id: "r13", question: "Which pair is odd?", options: ["(2,3)", "(4,5)", "(6,7)", "(8,9)"], correctAnswer: "(8,9)" },
    { id: "r14", question: "Book : Author :: Painting : ?", options: ["Canvas", "Artist", "Frame", "Color"], correctAnswer: "Artist" },
    { id: "r15", question: "10, 20, 40, 80, ?", options: ["120", "140", "160", "180"], correctAnswer: "160" },
    { id: "r16", question: "Which is different?", options: ["Monday", "Tuesday", "January", "Wednesday"], correctAnswer: "January" },
    { id: "r17", question: "A : Z :: B : ?", options: ["X", "Y", "W", "V"], correctAnswer: "Y" },
    { id: "r18", question: "1, 4, 9, 16, ?", options: ["20", "24", "25", "30"], correctAnswer: "25" },
    { id: "r19", question: "Fish : Water :: Bird : ?", options: ["Sky", "Air", "Cloud", "Wind"], correctAnswer: "Air" },
    { id: "r20", question: "Odd one out", options: ["Car", "Bus", "Train", "Spoon"], correctAnswer: "Spoon" },
  ],
  english: [
    { id: "e1", question: "Choose the correct spelling.", options: ["Recieve", "Receive", "Receeve", "Receve"], correctAnswer: "Receive" },
    { id: "e2", question: "Opposite of Happy?", options: ["Glad", "Sad", "Smile", "Excited"], correctAnswer: "Sad" },
    { id: "e3", question: "Choose the noun.", options: ["Run", "Beautiful", "School", "Quickly"], correctAnswer: "School" },
    { id: "e4", question: "Synonym of Fast?", options: ["Slow", "Rapid", "Weak", "Bad"], correctAnswer: "Rapid" },
    { id: "e5", question: "Select the correct article.", options: ["a", "an", "the", "all"], correctAnswer: "an" },
    { id: "e6", question: "Choose the verb.", options: ["Happy", "Run", "Beautiful", "Green"], correctAnswer: "Run" },
    { id: "e7", question: "Opposite of Hot?", options: ["Cold", "Warm", "Cool", "Freezing"], correctAnswer: "Cold" },
    { id: "e8", question: "Choose the adjective.", options: ["Jump", "Beautiful", "Run", "Quickly"], correctAnswer: "Beautiful" },
    { id: "e9", question: "Synonym of Big?", options: ["Small", "Large", "Tiny", "Short"], correctAnswer: "Large" },
    { id: "e10", question: "Choose correct spelling.", options: ["Occured", "Occurred", "Occurrd", "Occuured"], correctAnswer: "Occurred" },
    { id: "e11", question: "Opposite of Dark?", options: ["Dim", "Light", "Bright", "Shadow"], correctAnswer: "Bright" },
    { id: "e12", question: "Choose the adverb.", options: ["Run", "Beautiful", "Quickly", "School"], correctAnswer: "Quickly" },
    { id: "e13", question: "Synonym of Happy?", options: ["Sad", "Joyful", "Angry", "Tired"], correctAnswer: "Joyful" },
    { id: "e14", question: "Choose correct spelling.", options: ["Sieze", "Seize", "Seaze", "Sease"], correctAnswer: "Seize" },
    { id: "e15", question: "Opposite of Begin?", options: ["Start", "Continue", "End", "Begin"], correctAnswer: "End" },
    { id: "e16", question: "Synonym of Small?", options: ["Big", "Large", "Tiny", "Huge"], correctAnswer: "Tiny" },
    { id: "e17", question: "Choose the correct pronoun.", options: ["him", "his", "he", "her"], correctAnswer: "him" },
    { id: "e18", question: "Opposite of Young?", options: ["New", "Old", "Fresh", "Recent"], correctAnswer: "Old" },
    { id: "e19", question: "Choose correct spelling.", options: ["Beleive", "Believe", "Belive", "Beleave"], correctAnswer: "Believe" },
    { id: "e20", question: "Synonym of Smart?", options: ["Dumb", "Intelligent", "Slow", "Lazy"], correctAnswer: "Intelligent" },
  ],
};

export const testPapers = [
  {
    id: "math-1",
    category: "math",
    title: "Mathematics Mock Test 1",
    duration: 20,
    totalQuestions: 20,
    description: "Basic math assessment covering arithmetic operations",
  },
  {
    id: "math-2",
    category: "math",
    title: "Mathematics Mock Test 2",
    duration: 20,
    totalQuestions: 20,
    description: "Advanced math assessment covering algebra and geometry",
  },
  {
    id: "reasoning-1",
    category: "reasoning",
    title: "Reasoning Assessment",
    duration: 20,
    totalQuestions: 20,
    description: "Logical reasoning and pattern recognition test",
  },
  {
    id: "english-1",
    category: "english",
    title: "English Grammar Test",
    duration: 20,
    totalQuestions: 20,
    description: "English grammar and vocabulary assessment",
  },
];
